// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1imV9jFQn73o0V9bHJeg16K--Z6zFKg0',
    appId: '1:623888856256:web:7e2eeec6058285767ce925',
    messagingSenderId: '623888856256',
    projectId: 'on-time-fix',
    authDomain: 'on-time-fix.firebaseapp.com',
    storageBucket: 'on-time-fix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEakJ8f8wlUdqHBnB-x5hFnYBHomnBs3M',
    appId: '1:623888856256:android:456604271ceb1be17ce925',
    messagingSenderId: '623888856256',
    projectId: 'on-time-fix',
    storageBucket: 'on-time-fix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5zgeGHsOr-JJgzTZS7paqcP3_NqhPr8',
    appId: '1:623888856256:ios:c6d10a0421ad35d47ce925',
    messagingSenderId: '623888856256',
    projectId: 'on-time-fix',
    storageBucket: 'on-time-fix.firebasestorage.app',
    iosBundleId: 'com.example.onTimeFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5zgeGHsOr-JJgzTZS7paqcP3_NqhPr8',
    appId: '1:623888856256:ios:c6d10a0421ad35d47ce925',
    messagingSenderId: '623888856256',
    projectId: 'on-time-fix',
    storageBucket: 'on-time-fix.firebasestorage.app',
    iosBundleId: 'com.example.onTimeFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1imV9jFQn73o0V9bHJeg16K--Z6zFKg0',
    appId: '1:623888856256:web:9a695a02e22555cc7ce925',
    messagingSenderId: '623888856256',
    projectId: 'on-time-fix',
    authDomain: 'on-time-fix.firebaseapp.com',
    storageBucket: 'on-time-fix.firebasestorage.app',
  );
}
